# Generated by Django 5.0.6 on 2024-09-22 06:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.FileField(upload_to='static/uploads')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
