# Generated by Django 5.0.6 on 2024-09-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingapi', '0002_alter_blogging_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='content',
            field=models.TextField(),
        ),
    ]
