# Generated by Django 5.0.6 on 2024-09-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingapi', '0007_alter_category_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogging',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloggingapi.category'),
        ),
    ]
