# Generated by Django 5.0.6 on 2024-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingapi', '0010_alter_blogging_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='content',
            field=models.TextField(blank=True, default=True, null=True),
        ),
    ]
