# Generated by Django 5.1.4 on 2025-01-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingapi', '0013_alter_blogging_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='content',
            field=models.TextField(default=True, null=True),
        ),
    ]
